# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [1]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [2]:
import tensorflow as tf
print(tf.__version__)

2.0.0


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [4]:
from sklearn.datasets import load_iris
data = load_iris()
type(data)

sklearn.utils.Bunch

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [0]:
features = data.data
target = data.target

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(features,target,test_size=0.25,random_state=3)
print('Train set size {} {}'.format(x_train.shape,y_train.shape))
print('Test set size {} {}'.format(x_test.shape,y_test.shape))
x_train[:3]

Train set size (112, 4) (112,)
Test set size (38, 4) (38,)


array([[6.4, 2.7, 5.3, 1.9],
       [6.2, 2.2, 4.5, 1.5],
       [6.4, 2.8, 5.6, 2.1]])

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [7]:
y_train = tf.keras.utils.to_categorical(y_train, num_classes=3)
y_test = tf.keras.utils.to_categorical(y_test, num_classes=3)
print(y_train.shape)


(112, 3)


In [8]:
y_train[:5]

array([[0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]], dtype=float32)

## Question 5

### Initialize a sequential model
- Define a sequential model

In [0]:
model = tf.keras.models.Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [0]:
model.add(tf.keras.layers.Dense(3, input_shape=(4,),activation='softmax'))

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [0]:
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [13]:
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=100)

Train on 112 samples, validate on 38 samples
Epoch 1/100
112/112 [==============================] - 1s 5ms/sample - loss: 2.7386 - accuracy: 0.3125 - val_loss: 1.6346 - val_accuracy: 0.3947
Epoch 2/100
112/112 [==============================] - 0s 222us/sample - loss: 1.6264 - accuracy: 0.3125 - val_loss: 1.2849 - val_accuracy: 0.1316
Epoch 3/100
112/112 [==============================] - 0s 224us/sample - loss: 1.3145 - accuracy: 0.1161 - val_loss: 1.2082 - val_accuracy: 0.2105
Epoch 4/100
112/112 [==============================] - 0s 229us/sample - loss: 1.2283 - accuracy: 0.2054 - val_loss: 1.1679 - val_accuracy: 0.2632
Epoch 5/100
112/112 [==============================] - 0s 230us/sample - loss: 1.1872 - accuracy: 0.2411 - val_loss: 1.1283 - val_accuracy: 0.2632
Epoch 6/100
112/112 [==============================] - 0s 196us/sample - loss: 1.1412 - accuracy: 0.2857 - val_loss: 1.1000 - val_accuracy: 0.2632
Epoch 7/100
112/112 [==============================] - 0s 223us/sample - lo

## Question 10

### Make predictions
- Predict labels on one row

In [14]:
y_predicted = model.predict(x_test)
y_predicted[:3]

array([[0.83714974, 0.10537941, 0.05747084],
       [0.81002283, 0.12566939, 0.06430771],
       [0.8497275 , 0.09821844, 0.05205395]], dtype=float32)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [15]:
y_test[:3]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)



---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [17]:
import tensorflow as tf
print(tf.__version__)

2.0.0


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [0]:
# run this cell to upload file if you are using google colab
#

In [20]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [21]:
import numpy as np
import pandas as pd

df = pd.read_csv('/content/drive/My Drive/prices.csv')
df.head()

date symbol        open  ...         low        high     volume
0  2016-01-05 00:00:00   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1  2016-01-06 00:00:00   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2  2016-01-07 00:00:00   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3  2016-01-08 00:00:00   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4  2016-01-11 00:00:00   WLTW  117.010002  ...  114.089996  117.330002  1408600.0

[5 rows x 7 columns]

In [22]:
df.shape

(851264, 7)

In [0]:
df.drop(columns=['date','symbol'],inplace=True)


In [24]:
df.columns

Index(['open', 'close', 'low', 'high', 'volume'], dtype='object')

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [0]:
df1 = df[:1000]

In [26]:
df1.shape

(1000, 5)

In [27]:
df1.head()

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [0]:
X = df1.drop(columns='volume')

In [29]:
X.head()

open       close         low        high
0  123.430000  125.839996  122.309998  126.250000
1  125.239998  119.980003  119.940002  125.540001
2  116.379997  114.949997  114.930000  119.739998
3  115.480003  116.620003  113.500000  117.440002
4  117.010002  114.970001  114.089996  117.330002

In [0]:
y = df1['volume'] / 10000000

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [0]:
y = np.array(y)
X = np.array(X)

In [0]:
y = y.astype(np.float32)
X = X.astype(np.float32)

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [0]:
X = tf.math.l2_normalize(X)

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [0]:
W = tf.zeros(shape=(4, 1))
b = tf.zeros(shape=(1))

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [0]:
def prediction(features, W, b):
    y_pred = tf.add(tf.matmul(features, W), b)
    return y_pred

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [0]:
def loss(y_actual, y_predicted):
    diff = y_actual - y_predicted
    sqr = tf.square(diff)
    avg = tf.reduce_mean(sqr)
    return avg

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
def train(x, y_actual, w, b, learning_rate=0.01):
    
    # Record mathematical operations on 'tape' to calculate loss
    with tf.GradientTape() as t:
        t.watch([w,b])
        current_prediction = prediction(x, w, b)
        current_loss = loss(y_actual, current_prediction)
    
    # Calculate Gradients for Loss with respect to Weights and Bias
    dw, db = t.gradient(current_loss,[w, b])
    
    # Update Weights and Bias
    w = w - learning_rate * dw
    b = b - learning_rate * db
    
    return w, b

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [38]:
for i in range(100):    
    W, b = train(X, y, W, b)
    print('Current Training Loss on iteration', i, loss(y, prediction(X, W, b)).numpy())

Current Training Loss on iteration 0 2.3616786
Current Training Loss on iteration 1 2.3509305
Current Training Loss on iteration 2 2.34061
Current Training Loss on iteration 3 2.3306973
Current Training Loss on iteration 4 2.321179
Current Training Loss on iteration 5 2.312037
Current Training Loss on iteration 6 2.303258
Current Training Loss on iteration 7 2.2948263
Current Training Loss on iteration 8 2.2867281
Current Training Loss on iteration 9 2.278953
Current Training Loss on iteration 10 2.2714846
Current Training Loss on iteration 11 2.2643125
Current Training Loss on iteration 12 2.257422
Current Training Loss on iteration 13 2.2508075
Current Training Loss on iteration 14 2.2444534
Current Training Loss on iteration 15 2.2383513
Current Training Loss on iteration 16 2.232492
Current Training Loss on iteration 17 2.2268639
Current Training Loss on iteration 18 2.221459
Current Training Loss on iteration 19 2.216269
Current Training Loss on iteration 20 2.2112837
Current Trai

### Observe values of Weight
- Print the updated values

In [39]:
W.numpy()

array([[0.00547828],
       [0.00548819],
       [0.00542273],
       [0.00553312]], dtype=float32)

### Observe values of Bias
- Print the updated values

In [40]:
b.numpy()

array([0.46076566], dtype=float32)