# Hypothesis Testing

The purpose of the test is to tell if there is any significant difference between two data sets.



## Overview

This module covers,

1) One sample and Two sample t-tests

2) ANOVA

3) Type I and Type II errors

4) Chi-Squared Tests

## Question 1 

*A student is trying to decide between two GPUs. He want to use the GPU for his research to run Deep learning algorithms, so the only thing he is concerned with is speed.*

*He picks a Deep Learning algorithm on a large data set and runs it on both GPUs 15 times, timing each run in hours. Results are given in the below lists GPU1 and GPU2.*

In [1]:
from scipy import stats 
import numpy as np

In [2]:
GPU1 = np.array([11,9,10,11,10,12,9,11,12,9,11,12,9,10,9])
GPU2 = np.array([11,13,10,13,12,9,11,12,12,11,12,12,10,11,13])

#Assumption: Both the datasets (GPU1 & GPU 2) are random, independent, parametric & normally distributed

Hint: You can import ttest function from scipy to perform t tests 

**First T test**

*One sample t-test*

Check if the mean of the GPU1 is equal to zero.
- Null Hypothesis is that mean is equal to zero.
- Alternate hypothesis is that it is not equal to zero.

In [3]:
# Using scipy-stats method, for 1 sample, 2 tailed t-test

t_stat, p_value = stats.ttest_1samp(GPU1,0)
print(t_stat,p_value)

# From the p-value derived(less than alpha i.e. significance level), null-hypothesis can be rejected

34.056241516158195 7.228892044970457e-15


In [4]:
# calculation derived by not using stats method
mu = 0

In [5]:
n = GPU1.size
xbar = GPU1.mean()
se = GPU1.std()/np.sqrt(n-1)
print(n,xbar,se)

15 10.333333333333334 0.3034196632775998


In [6]:
t_statistics = (xbar - mu)/ se
print(t_statistics)

34.056241516158195


In [7]:
p_val = stats.t.cdf(t_statistics, df=n-1)
print((1-p_val)*2)

7.105427357601002e-15


## Question 2

Given,

Null Hypothesis : There is no significant difference between data sets

Alternate Hypothesis : There is a significant difference

*Do two-sample testing and check whether to reject Null Hypothesis or not.*

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html

In [8]:
t_stat, p_value = stats.ttest_ind(GPU1, GPU2)
print(t_stat, p_value)

# From the p-value derived(less than alpha-5% i.e. significance level), null-hypothesis can be rejected

-2.627629513471839 0.013794282041452725


## Question 3

He is trying a third GPU - GPU3.

In [9]:
GPU3 = np.array([9,10,9,11,10,13,12,9,12,12,13,12,13,10,11])

#Assumption: Both the datasets (GPU1 & GPU 3) are random, independent, parametric & normally distributed

*Do two-sample testing and check whether there is significant differene between speeds of two GPUs GPU1 and GPU3.*

#### Answer:

In [10]:
#Null Hypothesis : There is no significant difference between data sets
#Alternate Hypothesis : There is a significant difference
#Do two-sample testing and check whether to reject Null Hypothesis or not.

t_stat, p_value = stats.ttest_ind(GPU1, GPU3)
print(t_stat, p_value)

# From the p-value derived(greater than alpha-5% i.e. significance level) and failed to reject null-hypothesis 

-1.4988943759093303 0.14509210993138993


## ANOVA

## Question 4 

If you need to compare more than two data sets at a time, an ANOVA is your best bet. 

*The results from three experiments with overlapping 95% confidence intervals are given below, and we want to confirm that the results for all three experiments are not significantly different.*

But before conducting ANOVA, test equality of variances (using Levene's test) is satisfied or not. If not, then mention that we cannot depend on the result of ANOVA

In [11]:
import numpy as np

e1 = np.array([1.595440,1.419730,0.000000,0.000000])
e2 = np.array([1.433800,2.079700,0.892139,2.384740])
e3 = np.array([0.036930,0.938018,0.995956,1.006970])

#Assumption: All the 3 datasets (e1,e2 & e3) are random, independent, parametric & normally distributed

Perform levene test on the data

The Levene test tests the null hypothesis that all input samples are from populations with equal variances. Levene’s test is an alternative to Bartlett’s test bartlett in the case where there are significant deviations from normality.

source: scipy.org

#### Answer:

In [12]:
t_stats, p_value = stats.levene(e1,e2,e3)
print(t_stats,p_value)

# As the p-value is greater than alpha(5%). Hence, fail to reject the Null-Hypothesis (i.e variance are equal)

2.6741725711150446 0.12259792666001798


## Question 5

The one-way ANOVA tests the null hypothesis that two or more groups have the same population mean. The test is applied to samples from two or more groups, possibly with differing sizes.

use stats.f_oneway() module to perform one-way ANOVA test

In [13]:
F_stats, p_val = stats.f_oneway(e1,e2,e3)
print(F_stats, p_val)

# As p_val is greater than alpha(5%), fail to reject the null-hypothesis

2.51357622845924 0.13574644501798466


## Question 6

*In one or two sentences explain about **TypeI** and **TypeII** errors.*

#### Answer:

Type-I error(Alpha): 
- Rejecting the null-hypothesis when it is true(false-positive). 
- Alpha is the probability of Type-I error. Also, further (1-Alpha) is the probability of accepting(fail to reject) the null-hypothesis when it is true.

Type-II error(Beta) : 
- Fail to reject the null-hypothesis when it is false(false-negative)
- Beta is the probability of Type-II error. Similarly, (1-Beta) is the probabiltiy of rejecting the null-hypothesis when it is false.

Null-Hypothesis: Status-quo

## Question 7 

You are a manager of a chinese restaurant. You want to determine whether the waiting time to place an order has changed in the past month from its previous population mean value of 4.5 minutes. 
State the null and alternative hypothesis.

#### Answer:


From the manager perspective,

Null-Hypothesis : Average waiting time is greater than or equal to 4.5 minutes

Alternate Hypothesis: Average waiting time is less than 4.5 minutes

IMO, Alternate hypothesis may not be defined as average waiting time is not equal to 4.5 mins. As from the above given statement it can be inferred that earlier it was idenetified by restaurant management that the average waiting time was 4.5 mins and some pro-active/re-active technique/method was cosidered to reduce it. Further, to understand that the new method deployed reduces the waiting time or not. From business perpective the expectation is the new method shall reduce the waiting time (i.e alternate hypothesis)

## Chi square test

## Question 8

Let's create a small dataset for dice rolls of four players

In [14]:
import numpy as np

d1 = [5, 8, 3, 8]
d2 = [9, 6, 8, 5]
d3 = [8, 12, 7, 2]
d4 = [4, 16, 7, 3]
d5 = [3, 9, 6, 5]
d6 = [7, 2, 5, 7]

dice = np.array([d1, d2, d3, d4, d5, d6])

run the test using SciPy Stats library

Depending on the test, we are generally looking for a threshold at either 0.05 or 0.01. Our test is significant (i.e. we reject the null hypothesis) if we get a p-value below our threshold.

For our purposes, we’ll use 0.01 as the threshold.

use stats.chi2_contingency() module 

This function computes the chi-square statistic and p-value for the hypothesis test of independence of the observed frequencies in the contingency table

Print the following:

- chi2 stat
- p-value
- degree of freedom
- contingency



In [15]:
chi2_stat, p, dof, exp = stats.chi2_contingency(dice)
print(chi2_stat, p, dof, exp)

# From the p-value derived(7.76) whith Alpha(1%), fail to reject null-hypothesis

23.315671914716496 0.07766367301496693 15 [[ 5.57419355  8.20645161  5.57419355  4.64516129]
 [ 6.50322581  9.57419355  6.50322581  5.41935484]
 [ 6.73548387  9.91612903  6.73548387  5.61290323]
 [ 6.96774194 10.25806452  6.96774194  5.80645161]
 [ 5.34193548  7.86451613  5.34193548  4.4516129 ]
 [ 4.87741935  7.18064516  4.87741935  4.06451613]]


## Question 9

### Z-test

Get zscore on the above dice data using stats.zscore module from scipy. Convert zscore values to p-value and take mean of the array.

In [16]:
z_score = stats.zscore(dice)
print(z_score)

[[-0.46291005 -0.18884739 -1.83711731  1.44115338]
 [ 1.38873015 -0.64208114  1.22474487  0.        ]
 [ 0.9258201   0.7176201   0.61237244 -1.44115338]
 [-0.9258201   1.62408759  0.61237244 -0.96076892]
 [-1.38873015  0.03776948  0.          0.        ]
 [ 0.46291005 -1.54854863 -0.61237244  0.96076892]]


In [17]:
'''
From the manual calculation of z-score and p-values for the example given in the folllowing
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.zscore.html

a = np.array([ 0.7972,  0.0767,  0.4383,  0.7866,  0.8091,
               0.1954,  0.6307,  0.6599,  0.1065,  0.0508])

computed mean : 0.45511999999999986 
computed std: 0.30346538451691657 

z = (a[0] - a.mean())/a.std() #1.1272455359103108
stats.norm.cdf(z) #0.8701806586264019

Above as the value is right of mean it shall be 1-cdf. Where only cdf give 0.87 whereas .ndtr gives 0.12981934


z1= (a[1] - a.mean()) / a.std() #-1.246995602488247
stats.norm.cdf(z1) #0.8938004449969086


Compute the zscore and p-value for the entire array
zscore = stats.zscore(a)

1 - scipy.special.ndtr(zscore)

Infer the .ndtr is apt method to use
'''
import scipy
p_values = 1 - scipy.special.ndtr(z_score)
print(p_values)

[[0.67828558 0.57489379 0.96690371 0.07477068]
 [0.08245741 0.73958975 0.11033568 0.5       ]
 [0.17726974 0.23649578 0.27014569 0.92522932]
 [0.82273026 0.05217856 0.27014569 0.83166582]
 [0.91754259 0.48493574 0.5        0.5       ]
 [0.32171442 0.93925487 0.72985431 0.16833418]]


## Question 10

A Paired sample t-test compares means from the same group at different times.

The basic two sample t-test is designed for testing differences between independent groups. 
In some cases, you might be interested in testing differences between samples of the same group at different points in time. 
We can conduct a paired t-test using the scipy function stats.ttest_rel(). 

In [18]:
before= stats.norm.rvs(scale=30, loc=100, size=500) ## Creates a normal distribution with a mean value of 100 and std of 30
after = before + stats.norm.rvs(scale=5, loc=-1.25, size=500)

Test whether a weight-loss drug works by checking the weights of the same group patients before and after treatment using above data.

In [19]:
# Null-Hypothesis : No differences 
# Alternate-Hypothseis : Differences are there

t_stats, p_val = stats.ttest_rel(before, after)
print(t_stats, p_val)

6.079866170329315 2.3929532728977423e-09


In [20]:
t_stat, p_value = stats.ttest_1samp(after-before, 0)
print(t_stat, p_value)

-6.079866170329315 2.3929532728977423e-09
